// Code generated by "stringer -type=Checksum"; DO NOT EDIT

package checksome

import "fmt"

const _Checksum_name = "UnknownSHA1SHA224SHA256SHA384SHA512SHA512_224SHA512_256"

var _Checksum_index = [...]uint8{0, 7, 11, 17, 23, 29, 35, 45, 55}

func (i Checksum) String() string {
	if i < 0 || i >= Checksum(len(_Checksum_index)-1) {
		return fmt.Sprintf("Checksum(%d)", i)
	}
	return _Checksum_name[_Checksum_index[i]:_Checksum_index[i+1]]
}
